# This should probably always be 1 for this bot.
replicaCount: 1

image:
  repository: benramsey/slack-irc
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Set to true for debug logging (per-message)
debug: false

# Note: the AUTH command results in an error message in the logs, but strangely
# upgraded pods don't seem to be able to connect/authenticate successfully
# with out it.  Maybe it's masking a race, or maybe I'm not understanding the error.
conf: |
  [
      {
          "nickname": "friendlybot",
          "server": "irc.freenode.net",
          "token": "THE-SLACK-TOKEN",
          "autoSendCommands": [
              ["MODE", "friendlybot", "+x"],
              ["NICK", "friendlybot"],
              ["AUTH", "MY-BOT-PASSWORD"],
              ["PRIVMSG", "NickServ", "IDENTIFY MY-BOT-PASSWORD"],
              ["JOIN", "#myircchannel"]
          ],
          "channelMapping": {
              "#myslackchannel": "#myircchannel"
          }
      }
  ]

