apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slack-irc-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "slack-irc-chart.name" . }}
    helm.sh/chart: {{ include "slack-irc-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    # Note: you can only have one bot logged into an IRC account at a time,
    # so Recreate blows away the old pod before spinning up the new one.
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "slack-irc-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "slack-irc-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config/
              readOnly: true
      {{- if .Values.debug }}
          env:
            - name: NODE_ENV
              value: "development"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "slack-irc-chart.fullname" . }}
          defaultMode: 0444
      
